In [1]:
import numpy as np

In [3]:
arr = np.arange(0,11)

In [4]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
arr[1] #calling like lists

1

In [9]:
arr[1:5] #indexing like lists 

array([1, 2, 3, 4])

In [14]:
arr[0:5] = 100 #broadcasts 100 to the chosen elements from array

In [15]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [16]:
arr = np.arange(0,11)

In [17]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
slices_of_arr = arr[0:6]

In [26]:
slices_of_arr

array([0, 1, 2, 3, 4, 5])

In [28]:
slices_of_arr[:] = 99
slices_of_arr

array([99, 99, 99, 99, 99, 99])

In [29]:
arr #broadcasts to the original array
# to not do this make a copy by arr.copy()

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [36]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])


In [37]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [40]:
arr_2d[1][1] # [row][column]

5

In [41]:
arr_2d[1,2]

6

In [46]:
arr_2d[:2,1:] #2D array slicing 

array([[2, 3],
       [5, 6]])

In [57]:
#conditional selection
arr = np.arange(1,11)

In [58]:
bool_arr = arr > 5


In [59]:
bool_arr # array of boolean values 

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [62]:
arr[bool_arr] #conditional array when a certain condition is met"

array([ 6,  7,  8,  9, 10])

In [64]:
arr[arr>5] # more efficient

array([ 6,  7,  8,  9, 10])

In [65]:
arr[arr<3]

array([1, 2])

In [66]:
#practice

new_arr = np.arange(50).reshape(10,5)
    
    


In [67]:
new_arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [68]:
print(new_arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]]


In [70]:
new_arr[2:5,1:4] #with slicing 

array([[11, 12, 13],
       [16, 17, 18],
       [21, 22, 23]])

In [75]:
# with conditional

new_arr[new_arr>10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
       28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44,
       45, 46, 47, 48, 49])