In [1]:
import numpy as np

In [3]:
arr = np.arange(0,11)

In [4]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
arr + arr # adds 2 arrays element by element

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [9]:
arr + 10 #adds scaler and works for all mul, div, sub ,add

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [10]:
1/0

ZeroDivisionError: division by zero

In [12]:
arr / arr # gives warning for 0/0

C:\Users\MITULA~1\AppData\Local\Temp/ipykernel_51100/1108587453.py:1: RuntimeWarning: invalid value encountered in true_divide
  arr / arr # gives warning for 0/0


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [15]:
arr / 0 #gives warning instead of error

C:\Users\MITULA~1\AppData\Local\Temp/ipykernel_51100/89068948.py:1: RuntimeWarning: divide by zero encountered in true_divide
  arr / 0 #gives warning instead of error
C:\Users\MITULA~1\AppData\Local\Temp/ipykernel_51100/89068948.py:1: RuntimeWarning: invalid value encountered in true_divide
  arr / 0 #gives warning instead of error


array([nan, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf])

In [16]:
#universal operations

In [17]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [18]:
np.max(arr)

10

In [19]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [21]:
np.log(arr)

C:\Users\MITULA~1\AppData\Local\Temp/ipykernel_51100/3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [ ]:
# amny more operations