In [5]:
my_list = [1,2,3]


In [8]:
my_list
import numpy as np

In [10]:
np.array(my_list)

array([1, 2, 3])

In [12]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
my_mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [23]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [25]:
np.zeros(3)

array([0., 0., 0.])

In [29]:
np.zeros((4,5))  #rows by columns

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [30]:
np.ones(3) #same as zeros but of 1

array([1., 1., 1.])

In [33]:
np.linspace(0,5,10) #gives enevly distributed numbers between 2 digits

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [34]:
#identity matrix

np.eye(4)


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [35]:
np.random.rand(5) #random numbers between 0 and 1 in 1D 

array([0.44479716, 0.4434323 , 0.89321627, 0.17053321, 0.02671835])

In [37]:
np.random.rand(5,5) #random numbers between 0 and 1 in 2D

array([[0.70047581, 0.83735897, 0.76500595, 0.41710743, 0.71252565],
       [0.90063558, 0.96191502, 0.69889214, 0.11444033, 0.87420939],
       [0.19524763, 0.58222506, 0.77564842, 0.8593201 , 0.05205333],
       [0.27183397, 0.06133885, 0.61077703, 0.71472337, 0.52095955],
       [0.75417766, 0.04614546, 0.09950768, 0.11272487, 0.1691703 ]])

In [40]:
np.random.randn(4,4) #random numbers around 0

array([[ 1.16196368,  1.66064695, -0.30922338, -0.3491896 ],
       [ 0.65696797, -0.59531212,  0.30130691,  1.23685298],
       [-0.29608461, -0.0539055 ,  1.40644641,  0.19852553],
       [ 0.39597014, -2.33662014,  1.74281148,  0.01744206]])

In [44]:
np.random.randint(1,100,20) #random integer between 2 numbers

array([24, 89, 29, 61, 30, 61, 98, 90, 61, 77, 70, 91, 58, 11, 60, 38, 92,
       45, 97, 48])

In [45]:
arr= np.arange(25)

In [46]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [47]:
randarr = np.random.randint(0,50,10)

In [48]:
randarr

array([13, 46, 17, 32, 34, 49,  3, 28, 25, 23])

In [52]:
arr.reshape(5,5) #exact numbers 

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [53]:
np.max(arr)

24

In [54]:
np.min(randarr)

3

In [55]:
randarr


array([13, 46, 17, 32, 34, 49,  3, 28, 25, 23])

In [56]:
randarr.argmax()

5

In [57]:
randarr.argmin()

6

In [60]:
arr = arr.reshape(5,5)
arr.shape

(5, 5)

In [61]:
arr.dtype

dtype('int32')