In [4]:
import numpy as np

In [5]:
my_list = [1,2,3]


In [6]:
np.array(my_list)

array([1, 2, 3])

In [7]:
len(np.linspace(1,10,50))


50

In [8]:
np.random.randn(4,4)

array([[ 0.1815463 , -1.81101256, -0.02261599, -1.51462996],
       [ 1.14669304,  0.5129579 ,  1.01358327,  0.88761934],
       [-0.62632177, -0.39294594,  1.80902315, -0.48265963],
       [-0.65127822, -0.9977968 , -0.2047501 , -0.07797995]])

In [9]:
arr = np.random.randint(0,10,5)
rr = np.arange(5,25)

In [10]:
arr

array([9, 7, 1, 1, 8])

In [11]:
rr


array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24])

In [12]:
rr.reshape(4,5)

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [13]:
arr.max()

9

In [14]:
arr.min()

1

In [15]:
arr.argmax()

0

In [16]:
arr.argmin()

2

In [17]:
rr.reshape(1,20)

array([[ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
        21, 22, 23, 24]])

In [18]:
rr.reshape(20,1)

array([[ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [19]:
arr.shape

(5,)

In [20]:
rr.reshape(1,20).shape

(1, 20)

In [21]:
arr.dtype

dtype('int32')

In [22]:
rr.dtype

dtype('int32')

In [23]:
rr


array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24])

In [24]:
rr[0:5] = 100
rr

array([100, 100, 100, 100, 100,  10,  11,  12,  13,  14,  15,  16,  17,
        18,  19,  20,  21,  22,  23,  24])

In [25]:
new_rr = rr.copy()

In [26]:
new_rr[0:5] = 30

In [27]:
new_rr

array([30, 30, 30, 30, 30, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24])

In [28]:
rr

array([100, 100, 100, 100, 100,  10,  11,  12,  13,  14,  15,  16,  17,
        18,  19,  20,  21,  22,  23,  24])

In [29]:
slice_of_rr = rr[0:5]

slice_of_rr

array([100, 100, 100, 100, 100])

In [30]:
slice_of_rr[:] = 143
slice_of_rr

array([143, 143, 143, 143, 143])

In [31]:
rr

array([143, 143, 143, 143, 143,  10,  11,  12,  13,  14,  15,  16,  17,
        18,  19,  20,  21,  22,  23,  24])

In [32]:
lola = np.zeros((20,20))
lola_length = lola.shape[0]


In [35]:
lola.shape

(20, 20)

In [38]:
for i in range(lola_length):
    lola[i] = i
    

In [46]:
lola[[1,2]]

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
        2., 2., 2., 2.]])

In [51]:
bool_rr = rr > 16

In [53]:
bool_rr

array([ True,  True,  True,  True,  True, False, False, False, False,
       False, False, False,  True,  True,  True,  True,  True,  True,
        True,  True])

In [55]:
rr[bool_rr]

array([143, 143, 143, 143, 143,  17,  18,  19,  20,  21,  22,  23,  24])

In [57]:
rr[rr>16]

array([143, 143, 143, 143, 143,  17,  18,  19,  20,  21,  22,  23,  24])

In [59]:
lop = np.arange(12)


In [60]:
lop

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [61]:
lop + lop


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22])

In [62]:
lop * lop

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121])

In [63]:
lop/lop

C:\Users\MITULA~1\AppData\Local\Temp/ipykernel_1300/531769980.py:1: RuntimeWarning: invalid value encountered in true_divide
  lop/lop


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [64]:
lop - lop

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [65]:
lop

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [66]:
lop ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121],
      dtype=int32)

In [67]:
lop ** 3

array([   0,    1,    8,   27,   64,  125,  216,  343,  512,  729, 1000,
       1331], dtype=int32)

In [68]:
np.sqrt(lop)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479])

In [69]:
np.exp(lop)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04])

In [70]:
np.max(lop)

11

In [71]:
np.sin(lop)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111, -0.99999021])

In [72]:
np.log(lop)

C:\Users\MITULA~1\AppData\Local\Temp/ipykernel_1300/3975737516.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(lop)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509, 2.39789527])